views/api.py
from datetime import datetime
import sys

from flask import Blueprint, redirect, request, session, url_for, make_response
import requests

from app import db
from helpers import login_required


api = Blueprint('api', __name__, url_prefix='/api/book')

@api.route("/add", methods=["POST"])
@login_required
def add_book():
    owner_id = session["user_id"]
    isbn = request.form.get("isbn")

    if len(isbn) != 13 and len(isbn) != 10:
        return "The ISBN provided is the wrong length (should be either 10 or 13)"

    r = requests.get(f'http://openlibrary.org/api/volumes/brief/isbn/{isbn}.json')
    book = r.json()["records"][list(r.json()["records"])[0]]
    print(book, file=sys.stderr)
    olid = book["olids"][0]
    title = book["data"]["title"]

    db.execute("INSERT INTO books (owner_id, olid, isbn, title) VALUES (?, ?, ?, ?)", owner_id, olid, isbn, title )

    return redirect(url_for("books.book_listing"))

@api.route("/delete", methods=["POST"])
@login_required
def delete_book():
    owner_id = session["user_id"]
    book_id = request.form.get("book_id")

    if len(db.execute("SELECT id FROM books WHERE id = ? AND owner_id = ?", book_id, owner_id)) != 0:
        db.execute("DELETE FROM books WHERE id = ? AND owner_id = ?", book_id, owner_id)
        db.execute("DELETE FROM requests WHERE book_id = ?", book_id)

    return redirect(url_for("books.book_listing"))

@api.route("/request", methods=["POST"])
@login_required
def request_book():
    values = {
        "book_id": request.form.get("book_id"),
        "user_id": session["user_id"],
        "time": datetime.now()
    }

    db.execute("INSERT INTO requests (book_id, user_id, time) VALUES (?, ?, ?)", *values.values())
    return values

@api.route("/cancel_request", methods=["POST"])
@login_required
def cancel_request():
    book_id = request.form.get("book_id")
    db.execute("DELETE FROM requests WHERE user_id = ? AND book_id = ?", session["user_id"], book_id)
    return redirect(url_for("books.book_details", book_id=book_id))

@api.route("/fulfill_request", methods=["POST"])
@login_required
def fulfill_request():
    book_id = request.form.get("book_id")
    user_id = session["user_id"]
    db.execute("DELETE FROM requests WHERE user_id = ? AND book_id = ?", user_id, book_id)
    db.execute("UPDATE books SET borrower_id = ? WHERE id = ?", user_id, book_id)
    return make_response(None, 204)

@api.route("/return", methods=["POST"])
@login_required
def return_book():
    db.execute("UPDATE books SET borrower_id = NULL WHERE id = ? AND borrower_id = ?", request.form.get("book_id"), session["user_id"])
    return redirect("/")

views/auth.py
from flask import Blueprint, render_template, redirect, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from app import  db

auth = Blueprint('auth', __name__, url_prefix='/auth')

@auth.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        # Return a version of the page with an error message
        def error(error):
            nonlocal username
            nonlocal password
            return render_template("register.html", username=username, password=password, error=error)

        username = request.form.get("username")
        password = request.form.get("password")
        confirmation = request.form.get("confirmation")

        if not username:
            return error("Empty username")

        if not password:
            return error("Empty password")

        if len(db.execute("SELECT id FROM users WHERE username = ?", username)) != 0:
            return error("Username already in use")

        if password != confirmation:
            return error("Password and confirmation do not match")

        hash = generate_password_hash(password)
        db.execute(
            "INSERT INTO users (username, hash) VALUES (?, ?)", username, hash
        )

        return redirect("/")

    else:
        return render_template("register.html")

@auth.route("/login", methods=["GET", "POST"])
def login():
    """Log user in"""

    # Forget any user_id
    session.clear()

    # User reached route via POST (as by submitting a form via POST)
    if request.method == "POST":

        # Return a version of the page with an error message
        def error(error):
            nonlocal username
            nonlocal password
            return render_template(url_for('auth.login'), username=username, password=password, error=error)

        username = request.form.get("username")
        password = request.form.get("password")
        # Ensure username was submitted
        if not username:
            return error("must provide username")

        # Ensure password was submitted
        elif not password:
            return error("must provide password")

        # Query database for username
        rows = db.execute(
            "SELECT * FROM users WHERE username = ?", username
        )

        # Ensure username exists and password is correct
        if len(rows) != 1 or not check_password_hash(
            rows[0]["hash"], password
        ):
            return error("invalid username and/or password")

        # Remember which user has logged in
        session["user_id"] = rows[0]["id"]

        # Redirect user to home page
        return redirect("/")

    # User reached route via GET (as by clicking a link or via redirect)
    else:
        return render_template("login.html")

@auth.route("/logout")
def logout():
    """Log user out"""

    # Forget any user_id
    session.clear()

    # Redirect user to login form
    return redirect("/")

views/books.py
from flask import Blueprint, redirect, render_template, session, url_for

from app import db
from helpers import login_required
import requests


books = Blueprint('books', __name__, url_prefix='/books')

@books.route("/")
@login_required
def books_listing():
    books = db.execute("SELECT id, isbn, title, borrower_id FROM books")

    return render_template("books.html", books=books)

@books.route("/<string:book_id>")
@login_required
def book_details(book_id):
    details = db.execute("SELECT * FROM books WHERE id = ?", book_id)
    if not details:
        return redirect(url_for('books.book_listing'))
    details = details[0]
    request = db.execute("SELECT request_id FROM requests WHERE book_id = ?", book_id)
    has_book = details["borrower_id"] == session["user_id"]
    is_owner = details["owner_id"] == session["user_id"]

    olid = details["olid"]

    book = requests.get(f'http://openlibrary.org/books/{olid}.json').json()
    work_id = book["works"][0]["key"]

    work = requests.get(f'http://openlibrary.org{work_id}.json').json()
    desc = work.get("description")
    text = []
    if desc:
        desc = desc["value"]
        text = desc.split('\n')

    return render_template("book_details.html", id=book_id, olid=olid, title=details["title"], subtitle=book.get("subtitle"), description=text, request=request, has_book=has_book, is_owner=is_owner)

templates/book_details.html
{% extends "layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}

    <img src="https://covers.openlibrary.org/b/olid/{{olid}}-M.jpg" style="float:left; margin-left: 10px; margin-right: 10px;">
    <h2>{{title}}</h2>
    {% if subtitle %}<h3 class="subtitle">{{subtitle}}</h3>{% endif %}

    {% if has_book%}
    <form action="{{url_for('api.return_book')}}" method="POST">
        <input type="number" name="book_id" hidden value="{{id}}">
        <input type="submit" value="Return Book">
    </form>
    {% else %}
    {% if not request %}
    <form action="{{url_for('api.request_book')}}" method="POST">
        <input type="number" name="book_id" hidden value="{{id}}">
        <input type="submit" value="Request Book">
    </form>
    {% else %}
    <form action="{{url_for('api.cancel_request')}}" method="POST">
        <input type="number" name="book_id" hidden value="{{id}}">
        <input type="submit" value="Cancel Request">
    </form>
    {% endif %}
    {% endif %}

    {% if is_owner %}

    <button id="deleteBook">Delete book</button>
    {% endif %}
    <div>
        {% for para in description %}
        <p>
            {{para}}
        </p>
        {% endfor %}
    </div>

    {% if is_owner %}
    <script>

        var form = document.getElementById("deleteBook");


        function reqListener() {
            window.close();
        }

        function deleteBook() {
            if (!confirm("Delete this book?")) {
                return;
            }

            // Construct a FormData instance
            const formData = new FormData();
            formData.append("book_id", "{{id}}");

            const req = new XMLHttpRequest();
            req.addEventListener("load", reqListener);
            req.open("POST", "{{url_for('api.delete_book')}}");
            req.send(formData);
        }

        form.addEventListener("click", deleteBook);
    </script>
    {% endif %}
{% endblock %}

templates/books.html
{% extends "layout.html" %}

{% block title %}
    Books
{% endblock %}

{% block body %}
<div class="page-center">
    <h1>Books</h1>
    <button id="showDialog">Add Book</button>

    <div class="grid-container">
    {% for book in books %}
        <div>
            <img src="https://covers.openlibrary.org/b/isbn/{{book.isbn}}-S.jpg" loading="lazy">
            <p class="book-title {% if book.borrower_id %}book-taken{% else %}book-available{% endif %}"><a href="{{url_for('books.book_details', book_id=book.id)}}" target="_blank">{{book.title}}</a></p>
        </div>
    {% endfor %}
    </div>

    <dialog id="addBookDialog">
        <button id="closeDialog"n>Close</button>
        Add Book
        <form action="{{url_for('api.add_book')}}" method="post" class="form" id="addBook">
            <input type="number" name="isbn" placeholder="ISBN Number">
            <input type="submit" value="Submit">
        </form>
    </dialog>


</div>

<script>
    var button = document.getElementById("showDialog");
    var dialog = document.getElementById("addBookDialog");
    var button2 = document.getElementById("closeDialog");

    button.addEventListener("click", () => {
        dialog.showModal();
    });

    button2.addEventListener("click", () => {
        dialog.close();
    });
</script>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock %}

{% block style %}
    .card-list {
        display: grid;
        grid-template-columns: repeat(auto-fill, 200px);
        gap: 10px;
        grid-auto-rows: 1fr;
        overflow: auto; white-space: nowrap;
    }

    .card-list * {
        white-space: normal;
        text-align: center;
    }

{% endblock %}

{% block body %}
<div style="padding:20px;">
    <h2>Hello, {{name}}</h2>
    <div style="display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 10px;
    grid-auto-rows: minmax(100px, auto);">
        <div class="card" style="grid-column: 1; grid-row: 1/3;">
            <h3 class="card-title">Info</h3>

            <h4>Stats</h4>
            <ul>
                <li>Number of books: {{book_count}}</li>
                <li>Number of users: {{users}}</li>
                <br>
                <li>You have {{user_books}} books registered</li>
                <li>You have {{user_takeouts | length}} books currently taken out.</li>
                <li>You are waiting on {{user_requests}} books.</li>
            </ul>
        </div>
        <div class="card" style="grid-column: 2/4; grid-row: 1;">
            <h3 class="card-title">Books Requested</h3>
            <div class="card-list">
                {% for book in requested_books %}
                <div id="{{book.id}}">
                    <img src="https://covers.openlibrary.org/b/isbn/{{book.isbn}}-S.jpg" loading="lazy" class="center">
                    <p class="book-title book-requested"><a href="{{url_for('books.book_details', book_id=book.id)}}" target="_blank"><strong>{{book.username}}</strong> requested <i>{{book.title}}</i></a></p>
                    <button onclick="fulfillRequest({{book.id}})">Book received?</button>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="card" style="grid-column: 2/4; grid-row: 2;">
            <h3 class="card-title">Books you've taken out</h3>

            <div class="card-list">
            {% for book in user_takeouts %}
                <div>
                    <img src="https://covers.openlibrary.org/b/isbn/{{book.isbn}}-S.jpg" loading="lazy">
                    <p class="book-title book-requested"><a href="{{url_for('books.book_details', book_id=book.id)}}" target="_blank">{{book.title}}</a></p>
                </div>
            {% endfor %}
            </div>

        </div>
    </div>
</div>

<script>
    function fulfillRequest(book_id) {
        // Construct a FormData instance
        const formData = new FormData();
        formData.append("book_id", book_id);

        const req = new XMLHttpRequest();
        req.open("POST", "{{url_for('api.fulfill_request')}}");
        req.onload = function() {
            if (req.status === 200) {
                var item = document.getElementById(book_id);
                item.remove()
            }
        }
        req.send(formData);
    }
</script>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Mini Library - {% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link href="/static/style.css" rel="stylesheet">
        <style>{% block style %}{% endblock %}</style>
    </head>
    <body>
        <header>
            <a href="/"><span id="logo"><img src="/static/LibrariesIcon.svg"> Mini Library</span></a>
            <!-- <div class="separator"> -->
            <div>
                <a href="/books">Books</a>
            </div>

            <div id="account-management">
                {% if session["user_id"] %}
                <a href="{{url_for('auth.logout')}}">Log out</a>
                {% else %}
                <a href="{{url_for('auth.register')}}">Register</a>
                <a href="{{url_for('auth.login')}}">Log in</a>
                {% endif %}
            </div>
        </header>
        <main>
            {% block body %}{% endblock %}
        </main>
    </body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block title %}
    Log In
{% endblock %}

{% block body %}
    <div class="container" style="width: 600px; margin:auto;">
        <h2 style="text-align: center">Log In</h2>
        <form action="{{url_for('auth.login')}}" method="post" class="form">
            <input type="text" name="username" placeholder="Username" required {% if username %} value="{{username}}" {% endif %}>
            <input type="password" name="password" placeholder="Password" required {% if password %} value="{{password}}" {% endif %}>
            {% if error %}<p class="error">{{error}}</p>{% endif %}
            <input type="submit" value="Submit">
        </form>
    </div>

{% endblock %}

templates/register.html
{% extends "layout.html" %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <div class="container" style="width: 600px; margin:auto;">
        <h2 style="text-align: center">Register</h2>
        <form action="{{url_for('api.register')}}" method="post" class="form">
            <input type="text" name="username" placeholder="Username" required {% if username %} value="{{username}}" {% endif %}>
            <input type="password" name="password" placeholder="Password" required {% if password %} value="{{password}}" {% endif %}>
            <input type="password" name="confirmation" placeholder="Confirm Password" required>
            {% if error %}<p class="error">{{error}}</p>{% endif %}
            <input type="submit" value="Submit">
        </form>
    </div>

{% endblock %}